### ISSUE TITLE
Discussion: Annotate tokens

### ISSUE THREAD

**Issue by halfdan** [manorie/textoken#12]
I'm attempting to use this gem in a use case where I want to separate text (words) from punctuation. It would be great to have an "extended" option that would return tokens alongside their token type, i.e.:

```
Tokenize("This is Alfa.").tokens
=> ["This", "is", "Alfa", ".").tokens
Tokenize("This is Alfa.", options: [:extended]).tokens
=> [{ token: "This", type: "word"}, { token: "is", type: "word" }, ..., { token: ".", type: "punctuation"}]
```

Given the current options I think the existing types for "date", "phone", "number", "word", "punctuation" make most sense.
I'm not 100% sure if this is a good solution, but it would allow me to reconstruct the input text and mark anything that is a valid word.

Thoughts?

**Comment by thisiscetin** [comment]
I think you want to identify if a token is a date, phone, number included etc. with current regexps? 
First think coming to my mind is - I am sure there will be overlapping regexps if we keep adding more and more regexps to the file. But if we can pick a small regexp subset which we prefer like - numbers, words, date (more broader and less overlapping ones) that can work like a charm. Very good idea!

We can add more/modify regexps for this purpose.

**Comment by thisiscetin** [comment]
Want to make an experiment on or try implementing it? @halfdan

**Comment by halfdan** [comment]
Happy to hack something together for this!

**Comment by thisiscetin** [comment]
Nice! I would be happy to collaborate for that feature. First thing comes to my mind is public interface has two methods .tokens & .words we can add it like .extend . Lets open up a feature branch add some tests and split the work load.

**Comment by halfdan** [comment]
Sounds great - let's do it. We can add a couple failing tests and the work on getting them to run.

**Comment by thisiscetin** [comment]
Want me to add you as a collaborator to the project? Seems like you are interested and the product can go a long way imo.

**Comment by halfdan** [comment]
That'd be great, yes :)

**Comment by thisiscetin** [comment]
ok m8, adding, thanks.

**Comment by thisiscetin** [comment]
I have added a new branch called feature/extended. We can work on there and send a PR to development/master imo. Or we can work on directly on development branch also. Sent a collaboration invite.

**Comment by thisiscetin** [comment]
We can put a small rule that I have been encountering in opensource development at this small size. Lets not merge anything to development and master if both of us is not ok with it. And commit to the other branches however we like. Is it ok for you? We can put thumbs, mention each other or comment on PR like accepted. At least for this feature.

**Comment by halfdan** [comment]
Yep, absolutely. Was about to suggest the same :-) Proper review is always
good.

**Comment by halfdan** [comment]
I'll be on a flight today and will probably use the time to take a stab at this.

**Comment by halfdan** [comment]
@manorie Is there any place where we can chat? Do you use gitter / slack or any other IM?

**Comment by thisiscetin** [comment]
hi @halfdan I was on a vocation just came back sorry for late response. I use slack and gitter any room, do you use any which domain do you prefer to chat? Any public groups you are a member of?

**Comment by halfdan** [comment]
@manorie Sent you a message on gitter
