### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [manorie/textoken#14]
Dear @manorie ,

I've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository. 

Thank you for the project!

**Comment by thisiscetin** [comment]
Thanks for notification @arbox . It's done.

**Comment by arbox** [comment]
Thank you!
