### ISSUE TITLE
Fixnum is deprecated

### ISSUE THREAD

**Issue by ipatovanton** [manorie/textoken#15]
/Users/ipatov/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/textoken-1.1.2/lib/textoken/findings.rb:30: warning: constant ::Fixnum is deprecated

**Comment by thisiscetin** [comment]
Hi @ipatovanton , 

Thanks for reporting. I am a quite busy right now :/, I may cover this issue in the next couple weeks. If you want to send a PR you are more than welcome.

**Comment by thisiscetin** [comment]
We need support both old and new versions when moving to this change.
