### ISSUE TITLE
Tokenizing doesn't work for accented characters

### ISSUE THREAD

**Issue by halfdan** [manorie/textoken#9]
I just tried using this gem to tokenize an Icelandic sentence, but it seems to struggle with accented characters (or even any characters not in the english alphabet):

```
> Textoken('Hann er fullkomlega hunsaður. Ég er undrandi á því að hann vinni hérna enn.').tokens
 => ["Hann", "er", "fullkomlega", "hunsa", "ð", "ur", ".", "É", "g", "er", "undrandi", "á", "þ", "v", "í", "a", "ð", "hann", "vinni", "h", "é", "rna", "enn", "."]
```

**Comment by thisiscetin** [comment]
thanks for issue @halfdan I will have a look at it asap.

**Comment by halfdan** [comment]
@manorie Thanks! Took the liberty to PR this myself.

**Comment by thisiscetin** [comment]
thanks alot @halfdan I am very happy that you have volunteered and commited for it. I will close the PR now.

**Comment by halfdan** [comment]
@manorie My pleasure, thanks for merging!
